### ISSUE TITLE
[RFC] Git workflow

### ISSUE THREAD

**Issue by Skarlett** [the-computer-club/lynx#2]
[personal] ->  [testing] ->  [exported for use]
feature -> devel -> main (squashed devel for each version)

feature branches are **not** prefixed, 
base should be `devel`, the head is whatever changes you like.

backports branches are prefixed with "backport", 
base should be based on `devel`, the head can cherry pick from any branch.

automated branches are prefixed with "auto" 
base should be based on `devel`, and are treated the same as feature branches.

experimental branches are created once your feature is done, prefixed with "exp" 
a new branch should be created, based on `devel` latest, if feature and `devel`-latest bases differ.
merge feature into `exp` branch, and continue testing. when complete, PR to `devel`

once a `devel` branch is stable, it can be squashed into `main` for release.

**Comment by JeremiahSecrist** [comment]
Care to make a visual workflow of this to be integrated via docs?

**Comment by JeremiahSecrist** [comment]
We can also setup a PR template to make this simpler for users in the future.

**Comment by JeremiahSecrist** [comment]
I was also thinking main branch can be considered unstable to which then we lock into stable branch for releases
[personal fork / branch] -> pr review ->  [master -> main] -> [unstable (pending changes for stable)] -> [stable release branch] 
this workflow is similar to nixpkgs

**Comment by Skarlett** [comment]
![image](https://github.com/the-computer-club/lynx/assets/3759687/a2393ccb-4495-408a-a83e-bd41a7dff66d)

> I was also thinking main branch can be considered unstable to which then we lock into stable branch for releases
[personal fork / branch] -> pr review -> [master -> main] -> [unstable (pending changes for stable)] -> [stable release branch]
this workflow is similar to nixpkgs

I'm a strong believer that master/main should always contain stable code, and the latest version of stable. 

I can't see a particular reason why we would like to maintain a branch that many people are going to be walking on each others feet, especially on master.

The schematic I purpose allows maintains git blames in the `devel`, seperates stable code from experimental, and maintains a version log inside of master. While I intend to tag commits with versions aswell, I believe this approach to be more organized for the size of the repo.

I hope this illustration helps discern the process of maintaining git blame, and versioning inside of git. 

I should also note that the experimental branch can be omitted if `devel` has not changed since testing your feature

@JeremiahSecrist
